### ISSUE TITLE
Improve driver creation by implementing Factory

### ISSUE THREAD

**Issue by yuriy-khortashko** [berlinisimus/qaauto#1]
https://github.com/berlinisimus/qaauto/blob/866f52aab3ad7f879866f48acfdc1810f6fdb2f0/src/main/java/com/qa/auto/Driver.java#L13

Ініціалізація драйвера виглядає добре.
І її можна ще покращувати. 
В ідеалі можна зробити фабрику драйверів.

Тут дуже добре описано http://www.testautomationguru.com/selenium-webdriver-design-patterns-in-test-automation-factory-pattern/

Плюс є приклади як драйверам надавати кастомні налаштування

**Comment by berlinisimus** [comment]
fixed on dev, added browserFactory
