### ISSUE TITLE
Move navigation to index page to appropriate Page

### ISSUE THREAD

**Issue by yuriy-khortashko** [berlinisimus/qaauto#2]
https://github.com/berlinisimus/qaauto/blob/866f52aab3ad7f879866f48acfdc1810f6fdb2f0/src/main/java/com/qa/auto/Driver.java#L19

Навігацію на індекс сторінку краще забрати з метода, який ініціалізує драйвер. 
Теоретично, не всі тести можуть починатися з цієї сторінки.

В WebPage можна додати метод open, котрий буде робити навігейшн по урлі, і викликати WelcomePage->open після ініціалізації браузера

**Comment by berlinisimus** [comment]
fixed on dev, added method open()
